// This file is auto-generated by generateIconsIndex from /src/scripts/svgProcessor. Do not edit manually.

import bookmark from './svg/bookmark.svg';
import checkMark from './svg/checkMark.svg';
import comment from './svg/comment.svg';
import communities from './svg/communities.svg';
import dots from './svg/dots.svg';
import fullScreenClose from './svg/fullScreenClose.svg';
import fullScreenOpen from './svg/fullScreenOpen.svg';
import grok from './svg/grok.svg';
import home from './svg/home.svg';
import jobs from './svg/jobs.svg';
import lightning from './svg/lightning.svg';
import like from './svg/like.svg';
import logo from './svg/logo.svg';
import message from './svg/message.svg';
import notification from './svg/notification.svg';
import pause from './svg/pause.svg';
import play from './svg/play.svg';
import profile from './svg/profile.svg';
import replay from './svg/replay.svg';
import repost from './svg/repost.svg';
import search from './svg/search.svg';
import share from './svg/share.svg';
import views from './svg/views.svg';
import volumeOff from './svg/volumeOff.svg';
import volumeOn from './svg/volumeOn.svg';

export {
  bookmark,
  checkMark,
  comment,
  communities,
  dots,
  fullScreenClose,
  fullScreenOpen,
  grok,
  home,
  jobs,
  lightning,
  like,
  logo,
  message,
  notification,
  pause,
  play,
  profile,
  replay,
  repost,
  search,
  share,
  views,
  volumeOff,
  volumeOn
};
