

import fs from 'fs/promises';
import path from 'path';

const iconsDir = path.join(process.cwd(), 'src/icons/svg');
const indexFile = path.join(process.cwd(), 'src/icons/index.ts');


// export default async function generateIconsIndex() {
//   try {
//     // Check if the icons directory exists
//     try {
//       await fs.access(iconsDir);
//     } catch {
//       console.error('❌ Error: Icons directory not found');
//       process.exit(1);
//     }
//
//     // Read files in the directory
//     const files = await fs.readdir(iconsDir);
//     const svgFiles = files.filter(file => file.endsWith('.svg'));
//
//     // Create an array of imports
//     const imports = svgFiles.map(file => {
//       const name = path.basename(file, '.svg');
//       return `import ${name} from './svg/${file}';`;
//     });
//
//     // Create an export statement
//     const exports = `export {\n  ${svgFiles.map(file => path.basename(file, '.svg')).join(',\n  ')}\n};`;
//     // Generate index.ts content
//     const content = `${imports.join('\n')}\n\n${exports}\n`;
//
//     // Write to index.ts
//     await fs.writeFile(indexFile, content);
//
//     console.log('✅ index.ts file successfully generated with named exports!');
//   } catch (err) {
//     console.error('❌ SVG processing error:', err);
//     process.exit(1);
//   }
// }

export default async function generateIconsIndex() {
  try {
    // Check if the icons directory exists
    try {
      await fs.access(iconsDir);
    } catch {
      console.error('❌ Error: Icons directory not found');
      process.exit(1);
    }

    // Read files in the directory
    const files = await fs.readdir(iconsDir);
    const svgFiles = files.filter((file) => file.endsWith('.svg'));

    // Generate imports for each SVG file.
    // NOTE: These imports are auto-generated by the script; do not edit manually.
    const imports = svgFiles.map((file) => {
      const name = path.basename(file, '.svg');
      return `import ${name} from './svg/${file}';`;
    });

    // Create an export statement with the imported icons
    const exportsContent = `export {\n  ${svgFiles
      .map((file) => path.basename(file, '.svg'))
      .join(',\n  ')}\n};`;

    // Generate index.ts content with a warning comment at the top.
    const content = `// This file is auto-generated by generateIconsIndex from /src/scripts/svgProcessor. Do not edit manually.\n\n${imports.join(
      '\n'
    )}\n\n${exportsContent}\n`;

    // Write the generated content to index.ts
    await fs.writeFile(indexFile, content);

    console.log('✅ index.ts file successfully generated with named exports!');
  } catch (err) {
    console.error('❌ SVG processing error:', err);
    process.exit(1);
  }
}